---
# This playbook contains zabbix agent -> mysql plays
#
# https://s2.meissner.it/it/projects/mit-doc/wiki/MySQL-Überwachung_mit_Zabbix

# This does not work as of 2017-04-25 / ansible 2.2.2.0
#- include_role: name=mit.zabbix-agent.common task_from=get-zabbix-agent-path
- include: ../../mit.zabbix-agent.common/tasks/get-zabbix-agent-path.yml

- name: Copy zabbix mysql size2 script
  copy: src=zabbix-mysql-size2 dest=/usr/local/bin/zabbix-mysql-size2 mode=0755
  become: yes

- name: Copy zabbix mysql status2 script
  copy: src=zabbix-mysql-status2 dest=/usr/local/bin/zabbix-mysql-status2 mode=0755
  become: yes

- name: Copy zabbix mysql low level discovery (lld) script
  copy: src=zabbix-lld-mysql-databases dest=/usr/local/bin/zabbix-lld-mysql-databases mode=0755
  become: yes

- name: Add zabbix-agent configuration file
  copy: src=local-userparameter_mysql.conf
        dest={{ zabbix_agent_conf_dir }}
        mode=0644
  notify: restart zabbix-agent
  become: yes

